// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEM_Tmybgc1XtxvAGsF1jfeAOX-daXkNI',
    appId: '1:18825839717:web:e9afcec1e1bf42b234328c',
    messagingSenderId: '18825839717',
    projectId: 'enlight-f3a1d',
    authDomain: 'enlight-f3a1d.firebaseapp.com',
    databaseURL: 'https://enlight-f3a1d-default-rtdb.firebaseio.com',
    storageBucket: 'enlight-f3a1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7GZAhH0GTuW6-fzE0NyBmFyMZF37yfqA',
    appId: '1:18825839717:android:370ec1bc5e941f3034328c',
    messagingSenderId: '18825839717',
    projectId: 'enlight-f3a1d',
    databaseURL: 'https://enlight-f3a1d-default-rtdb.firebaseio.com',
    storageBucket: 'enlight-f3a1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLjKMODKiGQJ2PqmP2xw5VJAEndPiYCfk',
    appId: '1:18825839717:ios:f22830ae95c4efd834328c',
    messagingSenderId: '18825839717',
    projectId: 'enlight-f3a1d',
    databaseURL: 'https://enlight-f3a1d-default-rtdb.firebaseio.com',
    storageBucket: 'enlight-f3a1d.appspot.com',
    iosBundleId: 'com.example.enlight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLjKMODKiGQJ2PqmP2xw5VJAEndPiYCfk',
    appId: '1:18825839717:ios:f22830ae95c4efd834328c',
    messagingSenderId: '18825839717',
    projectId: 'enlight-f3a1d',
    databaseURL: 'https://enlight-f3a1d-default-rtdb.firebaseio.com',
    storageBucket: 'enlight-f3a1d.appspot.com',
    iosBundleId: 'com.example.enlight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEM_Tmybgc1XtxvAGsF1jfeAOX-daXkNI',
    appId: '1:18825839717:web:e1d535c12c5195a434328c',
    messagingSenderId: '18825839717',
    projectId: 'enlight-f3a1d',
    authDomain: 'enlight-f3a1d.firebaseapp.com',
    databaseURL: 'https://enlight-f3a1d-default-rtdb.firebaseio.com',
    storageBucket: 'enlight-f3a1d.appspot.com',
  );
}
